author:
  name: Thomas Huston
  email: tomhustonmusic@gmail.com
  social:
    instagram: tomhustonmusic
    github: TomHus
    email: tomhustonmusic@gmail.com
menu:
  - title: Blog
    url: /blog/
  - title: About
    url: /about/
title: Tom Huston
description: |
  Audio engineer and guitarist based in England
tagline: |
  Audio engineer and guitarist
keywords:
  - audio
  - engineering
  - music
  - guitar
logo: /assets/global/logo.png
favicon: /assets/global/favicon.ico
apple_touch_icon: /assets/global/logo.png
accent_image: /assets/global/tom.jpg
accent_color: rgb(191,87,13)
google_fonts: Roboto+Slab:700|Noto+Sans:400,400i,700,700i
font: Noto Sans, Helvetica, Arial, sans-serif
font_heading: Roboto Slab, Helvetica, Arial, sans-serif
url: https://tomhuston.co.uk
baseurl: "''"
lang: en
copyright: © 2024
permalink: /:categories/:year-:month-:day-:title/
paginate: 5
paginate_path: /blog/:num/
hydejack:
  dark_mode:
    dynamic: true
    icon: true
    always: false
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
theme: jekyll-theme-hydejack
optional_front_matter:
  remove_originals: false
readme_index:
  remove_originals: false
relative_links:
  collections: false
titles_from_headings:
  strip_title: true
  collections: true
kramdown:
  footnote_backlink: "'&#x21a9;&#xfe0e;'"
  math_engine: mathjax
  math_engine_opts:
    preview: true
    preview_as_code: true
compress_html:
  comments: "['<!-- ', ' -->']"
  clippings: all
  endings: all
sass:
  style: compressed
