author:
  name: Thomas Huston
  email: tomhustonmusic@gmail.com
  social:
    instagram: tomhustonmusic
    github: TomHus
menu:
  - title: Blog
    url: /blog/
title: Tom Huston
description: |
  Audio engineer and guitarist based in England
tagline: |
  Audio engineer and guitarist
keywords:
  - audio
  - engineering
  - music
  - guitar
logo: /assets/img/posts/icon.png
accent_image: /assets/img/tom.jpg
accent_color: rgb(191,87,13)
google_fonts: Roboto+Slab:700|Noto+Sans:400,400i,700,700i
font: Noto Sans, Helvetica, Arial, sans-serif
font_heading: Roboto Slab, Helvetica, Arial, sans-serif
url: https://tomhuston.co.uk
baseurl: "''"
lang: en
copyright: © 2024
permalink: /:categories/:year-:month-:day-:title/
paginate: 5
paginate_path: /blog/:num/
hydejack:
  dark_mode:
    dynamic: true
    icon: true
    always: false
theme: jekyll-theme-hydejack
optional_front_matter:
  remove_originals: false
readme_index:
  remove_originals: false
relative_links:
  collections: false
